FROM node:19.4-alpine

ENV NODE_ENV=production

WORKDIR  /app/usr/src

COPY package*json ./

RUN --mount=type=cache,target=/usr/src/app/.npm \
  npm set cache /usr/src/app/.npm && \
  npm ci --only=production

USER node

COPY --chown=node:node ./src/ .

EXPOSE 3000

CMD ["node","index.js"]